[tool.poetry]
name = "LISA"
version = "3.0.0.dev1"
description = "Linux Integration Services Automation"
authors = ["Andrew Schwartzmeyer <andrew@schwartzmeyer.com>", "Chi Song <song.chi@microsoft.com>"]
license = "Apache License 2.0"

[tool.poetry.dependencies]
python = "^3.8"
psutil = "^5.7.2"
pyyaml = "^5.3.1"
regex = "^2020.7.14"
retry = "^0.9.2"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.8.3"
flake8-black = "^0.2.1"
flake8-bugbear = "^20.1.4"
flake8-isort = "^3.0.1"
isort = "^4.3.21"
mypy = "^0.782"
pyls-black = "^0.4.6"
pyls-isort = "^0.1.1"
pyls-mypy = "^0.1.8"
python-language-server = "^0.34.1"
rope = "^0.17.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
