[tool.poetry]
name = "LISA"
version = "3.0.0.dev1"
description = "Linux Integration Services Automation"
authors = ["contributors <https://github.com/microsoft/lisa/graphs/contributors>"]
license = "MIT"

[tool.poetry.dependencies]
PyGObject = {version = "^3.38.0", platform = 'linux'}
PyYAML = "^5.4.1"
assertpy = "^1.1"
azure-identity = "^1.5.0"
azure-mgmt-compute = "^19.0.0"
azure-mgmt-marketplaceordering = "^1.1.0"
azure-mgmt-network = "^18.0.0"
azure-mgmt-resource = "^16.0.0"
azure-mgmt-storage = "^17.0.0"
dataclasses-json = "^0.5.2"
func-timeout = "^4.3.5"
paramiko = "^2.7.2"
pluggy = "^0.13.1"
pypiwin32 = {version = "^223", platform = "win32"}
pytest-html = "^3.1.1"
python = "^3.8"
python-dateutil = "^2.8.1"
retry = "^0.9.2"
spurplus = "^2.3.4"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
coverage = "^5.3"
flake8 = "^3.8.3"
flake8-black = "^0.2.1"
flake8-bugbear = "^21.3.2"
flake8-isort = "^4.0.0"
isort = "^5.5.3"
mypy = "^0.812"
pyls-black = "^0.4.6"
pyls-isort = "^0.2.0"
pyls-mypy = "^0.1.8"
python-language-server = "^0.36.2"
rope = "^0.18.0"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
