name: CI Workflow for LISAv3

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
      fail-fast: false
    steps:
      - name: Checkout repository to $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Setup bootstrap Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Poetry for Linux
        if: runner.os == 'Linux'
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "::add-path::$HOME/.poetry/bin"

      - name: Install Poetry for Windows
        if: runner.os == 'Windows'
        run: |
          (Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python
          echo "::add-path::$env:USERPROFILE\.poetry\bin"

      - name: Install Python dependencies
        run: poetry install

      - name: Run LISAv3 hello-world
        run: poetry run python lisa/main.py --debug

      - name: Run black/flake8/isort
        run: poetry run flake8

      - name: Run mypy static type checking
        run: poetry run mypy --strict --namespace-packages .

      - name: Run ShellCheck
        if: runner.os == 'Linux'
        uses: ludeeus/action-shellcheck@0.5.0
